language: go

go:
  - 1.14.x

env:
  global:
    - GO111MODULE=on
    - CODECOV_TOKEN="731a6a57-9ac6-43eb-8388-1dfb71308dd4"

install:
- go get honnef.co/go/tools/cmd/staticcheck
- go get github.com/google/addlicense
- go mod download

before_script:
- go vet ./...
- go build ./...
- go test -run xxxx ./...

script:
- make verifiers
- go test -race -short -coverprofile=coverage.txt ./...

after_success:
- bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $GOPATH/pkg/mod
    - $HOME/.cache/go-build
