version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    resource_class: small
    environment:
      CODECOV_TOKEN: 731a6a57-9ac6-43eb-8388-1dfb71308dd4
    docker:
      - image: circleci/golang:1.14.4
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: 
          name: download dependencies
          command: go mod download
      - run:
          name: install-verifiers
          command: go get honnef.co/go/tools/cmd/staticcheck github.com/google/addlicense
      - run:
          name: run-verifiers
          command: make verifiers
      - run: go test -v -race -coverprofile=coverage.txt -timeout 1800s ./...
      - codecov/upload:
          file: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}/coverage.txt
